name: currency-api
services:
  web:
    container_name: web
    image: nginx:alpine
    env_file: .env
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - type: bind
        source: ./nginx/default.conf.template
        target: /etc/nginx/templates/default.conf.template
        read_only: true
    networks:
      - appnet
    depends_on:
      - app
    restart: always

  app:
    container_name: app
    build:
      context: .
      args:
        APP_PORT: ${APP_PORT}
    image: yacr/currency_app:${VERSION:-v2}
    env_file: .env
    volumes:
      - type: bind
        source: ./config.yml
        target: /app/config.yml
        read_only: true
    networks:
      - appnet
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:${APP_PORT}/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

networks:
  appnet:
