name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker-compose version

      - name: Build and start containers
        run: |
          docker-compose up -d
          sleep 10

      - name: Check health endpoint
        run: |
          echo "Testing /health endpoint..."
          curl -f http://localhost:8081/health
          echo "Health check passed!"

      - name: Test /info endpoint
        run: |
          echo "Testing /info..."
          curl -f http://localhost:8081/info
          echo "Info check passed!"

      - name: Test /info/currency no query params
        run: |
          echo "Testing /info/currency..."
          curl -f "http://localhost:8081/info/currency"
          echo "Currency check (no query params) passed!"

      - name: Test /info/currency with date=2022-01-17
        run: |
          echo "Testing /info/currency?date=2022-01-17..."
          curl -f "http://localhost:8081/info/currency?date=2022-01-17"
          echo "Currency check with date passed!"

      - name: Test /info/currency with currency=USD and date=2022-01-17
        run: |
          echo "Testing /info/currency?currency=USD&date=2022-01-17..."
          curl -f "http://localhost:8081/info/currency?currency=USD&date=2022-01-17"
          echo "Currency check with currency and date passed!"

      - name: Test /info/currency with date in the past
        run: |
          echo "Testing /info/currency?currency=USD&date=1999-01-01..."
          curl -f "http://localhost:8081/info/currency?currency=USD&date=1999-01-01"
          echo "Check passed!"

      - name: Test /info/currency with future date
        run: |
          echo "Testing /info/currency?currency=AED&date=2024-01-01..."
          curl -f "http://localhost:8081/info/currency?currency=AED&date=2024-01-01"
          echo "Future date check passed!"

      - name: Shut down containers
        if: always()
        run: docker-compose down
